### ISSUE TITLE
Are Task IDs unique

### ISSUE THREAD

**Issue by pieterclaerhout** [thoas/bokchoy#1]
Imagine the following scenario:

* A certain queue contains is processing a task with the ID `1234`
* While that item is being processed, another task with the ID `1234` is submitted to the same queue

What will happen in this scenario?

Will it process both tasks or will it disregard the second one (as it's already processing)?

**Comment by thoas** [comment]
Task IDs are unique, there are based on [ulid](https://github.com/oklog/ulid)
