### ISSUE TITLE
ids no longer unique

### ISSUE THREAD

**Issue by TimSatke** [thoas/bokchoy#15]
071d83d Introduced a change that makes ids predictable and no longer random. 
This needs to be fixed, either replace ulid by a global counter or generate a random entropy source.

**Comment by TimSatke** [comment]
https://github.com/thoas/bokchoy/commit/071d83d8afc424df757473ce4a1d9c8bb299393a#commitcomment-36215537

**Comment by thoas** [comment]
indeed, I was not able to reproduce it on my local environment.

I have added a test to avoid this regression.

**Comment by TimSatke** [comment]
Fixed as of 18fe3d84330c918c9944cd6c4d5803ff14c2e030
