### ISSUE TITLE
2 panics when using custom redis broker

### ISSUE THREAD

**Issue by roman-vynar** [thoas/bokchoy#17]
Started using v0.2.0.
The example https://github.com/thoas/bokchoy/blob/master/examples/custom-broker/main.go stopped working because there are private fields which have to be initialized.
My code:

	broker, err = bokchoy.New(ctx, bokchoy.Config{},
		bokchoy.WithBroker(&bokchoy.RedisBroker{Client: myRedisClient, ClientType: "client"}),
type RedisBroker requires the following fields to be initialized:

	mu         *sync.Mutex
	queues     map[string]struct{}
and it's only done in newRedisBroker() which is private.

Without those 2 being initialized there are 2 panics:
1. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13c7912]

goroutine 79 [running]:
sync.(*Mutex).Lock(...)
	/usr/local/Cellar/go/1.13.7/libexec/src/sync/mutex.go:74
github.com/thoas/bokchoy.(*RedisBroker).consumeDelayed(0xc000545440, 0x1d0ec60, 0xc0000d0038, 0xc0003ceda0, 0x1d, 0x3b9aca00)
	/Users/weber/gopath/pkg/mod/github.com/thoas/bokchoy@v0.2.0/broker_redis.go:183 +0x42
```
2. 
```
panic: assignment to entry in nil map

goroutine 52 [running]:
github.com/thoas/bokchoy.(*RedisBroker).consumeDelayed(0xc0005bf0e0, 0x1d0ec20, 0xc0000380c8, 0xc0003882e0, 0x1d, 0x3b9aca00)
	/Users/weber/gopath/pkg/mod/github.com/thoas/bokchoy@v0.2.0/broker_redis.go:228 +0x1fe

```

So this makes impossible to use a custom broker (custom redis client in my case).

Thanks!

**Comment by thoas** [comment]
fixed, use `bokchoy.NewRedisBroker` func to initialize the redis broker, thank you for the report.

**Comment by roman-vynar** [comment]
It worked, thanks for the quick fix 🚀
