### ISSUE TITLE
Task may stop retrying on a specific condition

### ISSUE THREAD

**Issue by roman-vynar** [thoas/bokchoy#7]
I have been implementing bokchoy actively to replace our existing queue library. There is an issue with tasks being retried and when there are connectivity issues.

For example, I create a task which always fails and being retried every 5s.
Then I have the network connectivity issues to Redis and do hard-stop of my application.

When a task is retried there is a key in Redis `delay` containing task ID:
```
Type: Sorted Set (1 Members)

# | Score | Value
-- | -- | --
0 | 1566470199 | 01DJWE7F5WWCQ16BMYGHSK4CAX
```

However, if it happens to be a coincidence of redis connectivity issues and I stop an app, `delay` key is removed and the task remains always in queue with Failed status, MaxRetries >=0, some ETA.

To fix this we need whether to do some "transaction" on `delay` key so it is never lost or to create a cleanup goroutine to garbage collect Failed tasks having MaxRetries >=0 and re-queue them.

Also it would be great to have a method to tell a task to be re-processed if "max_retries" field is  removed (no more attempts left) or some other case like above. I know I can modify MaxRetries, ETA etc. but need to put a task id into `delay` set anyway.

Thanks!

**Comment by thoas** [comment]
hi @roman-vynar,

Sorry for the late reply, it's actually a bug I'm currently working on reshaping delayed tasks with redis transaction to avoid this kind of behavior.

**Comment by roman-vynar** [comment]
Thanks!
As a temporary measure I made a metric for monitoring if a task stays in queue for a long time (published_at>X and status any).

**Comment by thoas** [comment]
We are now relying on an atomic transaction for delayed tasks.
